name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 1.3.0
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: '>=1.23.0 <3.0.0'

dependencies:
  intl: ^0.15.1

dev_dependencies:
  test: ^1.3.0