name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 1.0.1
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  intl: '>=0.12.2 <0.15.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: any
