name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 0.1.0
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/timeago.dart

dependencies:
  intl: ">=0.12.2 <0.13.0"
dev_dependencies:
  test: ">=0.12.0-rc.1 <0.13.0"
  browser: any
