name: timeago_flutter_example
description: A Flutter example for timeago_flutter package on the top of timeago.

environment:
  sdk: ">=2.8.0  <3.0.0"

dependencies:
  timeago_flutter:
    path: ..
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
